timing complete for Raj Shorts

diff --git a/src/search/_bin/bin/prep b/src/search/_bin/bin/prep
--- a/src/search/_bin/bin/prep
+++ b/src/search/_bin/bin/prep
@@ -1,33 +1,34 @@
 #!/bin/bash
 
-workingDir=`pwd`
-scriptDir=`dirname $0`
-scriptName=`basename $0`
+workingDir=$(pwd)
+scriptDir=$(dirname $0)
+scriptName=$(basename $0)
 
-unitDir="/Users/rmercer/Projects/cmi/site/cmi-raj"
+# unitDir="/Users/rmercer/Projects/cmi/site/cmi-raj"
+unitDir="/Users/rmercer/Projects/cmi/site/cmi-sources/cmi-raj"
 awkFile="nwffacim.awk"
 debug=0
 
 source="raj"
 
 function syntax {
-  echo "prep -b <book> file"
-  echo " ex: prep -b grad chap01"
-  exit 1
+	echo "prep -b <book> file"
+	echo " ex: prep -b grad chap01"
+	exit 1
 }
 
 while getopts db: args; do
-    case $args in
-        b) book=$OPTARG;;
-        d) debug=1;;
-        *) syntax;;
-    esac
+	case $args in
+	b) book=$OPTARG ;;
+	d) debug=1 ;;
+	*) syntax ;;
+	esac
 done
 
-shift $(($OPTIND -1))
+shift $(($OPTIND - 1))
 
 if [[ -z $1 ]]; then
-  syntax
+	syntax
 fi
 
 #
@@ -47,19 +48,18 @@ unitDirName="${unitDir}/_${book}"
 unitFileName=${unitDirName}/${unit}.md
 
 if [ $debug == 1 ]; then
-  outputFile=${outputFile}.d.json
-  (gawk -f ${scriptDir}/${awkFile} -v debug=1 -v source=$source -v book=$book -v section=$section -v idx=$idx -v unit=$unit ${unitFileName} > $outputFile)
+	outputFile=${outputFile}.d.json
+	(gawk -f ${scriptDir}/${awkFile} -v debug=1 -v source=$source -v book=$book -v section=$section -v idx=$idx -v unit=$unit ${unitFileName} >$outputFile)
 else
-  outputFile=${outputFile}.json
-  #echo "gawk -f ${scriptDir}/${awkFile} -v debug=0 -v source=$source -v book=$book -v section=$section -v idx=$idx -v unit=$unit ${unitFileName} > $outputFile"
-  (gawk -f ${scriptDir}/${awkFile} -v debug=0 -v source=$source -v book=$book -v section=$section -v idx=$idx -v unit=$unit ${unitFileName} > $outputFile)
+	outputFile=${outputFile}.json
+	#echo "gawk -f ${scriptDir}/${awkFile} -v debug=0 -v source=$source -v book=$book -v section=$section -v idx=$idx -v unit=$unit ${unitFileName} > $outputFile"
+	(gawk -f ${scriptDir}/${awkFile} -v debug=0 -v source=$source -v book=$book -v section=$section -v idx=$idx -v unit=$unit ${unitFileName} >$outputFile)
 fi
 
 rc="$?"
 
 if [ "$rc" == "0" ]; then
-  echo "$outputFile created."
+	echo "$outputFile created."
 else
-  echo "conversion to json failed"
+	echo "conversion to json failed"
 fi
-
